# develop environment
# \u7AEF\u53E3
server:
  port: 8081

# \u6570\u636E\u5E93
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dingding?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: User
    password: 123456
#===== Use Redis in Spring =====#
#  redis:
#    # Redis\u6570\u636E\u5E93\u7D22\u5F15\uFF08\u9ED8\u8BA4\u4E3A0\uFF09
#    database: 0
#    # Redis\u670D\u52A1\u5668\u5730\u5740
#    host: localhost
#    # Redis\u670D\u52A1\u5668\u8FDE\u63A5\u7AEF\u53E3
#    port: 6379
#    # Redis\u670D\u52A1\u5668\u8FDE\u63A5\u5BC6\u7801\uFF08\u9ED8\u8BA4\u4E3A\u7A7A\uFF09
#    password:
#    # \u8FDE\u63A5\u6C60\u6700\u5927\u8FDE\u63A5\u6570\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09 \u9ED8\u8BA4 8
#    lettuce:
#      pool:
#        max-active: 8
#        # \u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09 \u9ED8\u8BA4 -1
#        max-wait: -1
#        # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5 \u9ED8\u8BA4 8
#        max-idle: 8
#        # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5 \u9ED8\u8BA4 0
#        min-idle: 0
#==========#

## mybatis config
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

# log\u914D\u7F6E: \u914D\u7F6E\u8F93\u51FA\u7684\u5730\u5740\u548C\u8F93\u51FA\u7EA7\u522B
logging:
  path: /user/local/log
  level:
    com.favorites: DEBUG
    org.springframework.web: INFO
    org.hibernate: ERROR
