dingding:
  security:
    cross:
      allow-origin-host: http://localhost:80[0-9]{2}, http://localhost:8848
    signing-key: dingding

logging:
  level:
    org:
      springframework:
        security: DEBUG

#spring:
#  security:
##    oauth2:
##      client:
##        registration:
##          client-id: dingding1
##          client-secret: dingding_secret1
##          authorization-grant-type: authorization_code
##          redirect-uri: http://example.com
##          scope: all
#    user:
#      password: 123456
