# Spring 配置
spring:
  application:
    # Spring 应用名称
    name: dingding-sso-server
  main:
    # Spring 容器的 Bean 覆盖方式 (在 Spring Boot 2.1 及以上版本增加该设定)
    allow-bean-definition-overriding: true
#  ## Spring Data JPA
#  ##-> <a href="https://blog.csdn.net/WZH577/article/details/99698187">Hibernate数据库配置项中命名策略说明</a>
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ### @Description 设计: 数据库结构不应该被框架操作
#      ddl-auto: none
#      ### @Tips 策略配置参照相应接口实现类的 API Docs (<class>SpringImplicitNamingStrategy</class>的实现有点坑)
#      naming:
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#    properties:
#      format_sql: true
#    show-sql: true
#    open-in-view: true
  mvc:
    ### 配置静态资源访问前缀
    ###-> @Reference <class>org.springframework.boot.autoconfigure.web.servlet.WebMvcProperties</class>
    static-path-pattern: /static/**
  ## 加载 dev 环境配置
  profiles:
    active: dev
    include: security
  ## 配置静态资源路径 (默认配置失效)
  resources:
    static-locations[0]: classpath:/static/