dingding:
  security:
    client-id: dingding_log_client
    client-secret: dingding_log_client_secrect1
    cross:
      allow-origin-host: http://localhost:8080
    signing-key: dingding
  sso:
    auth-server:
      root: http://127.0.0.1:9999/authorization-server
      endpoint:
        check_token: ${dingding.sso.auth-server.root}/oauth/check_token

logging:
  level:
    root: WARN
    org:
      springframework:
        web: INFO
        security: DEBUG

spring:
  redis:
    host: 127.0.0.1
    port: 6379
