server:
  port: 8301
  servlet:
    context-path: /user-service

spring:
  #  application:
  #    name: user-service
  ## Spring Data JPA
  ##-> <a href="https://blog.csdn.net/WZH577/article/details/99698187">Hibernate数据库配置项中命名策略说明</a>
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
    ### @Description 设计: 数据库结构不应该被框架操作
    ddl-auto: none
    ### @Tips 策略配置参照相应接口实现类的 API Docs (<class>SpringImplicitNamingStrategy</class>的实现有点坑)
    naming:
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      format_sql: true
    show-sql: true
    open-in-view: true
  ## 加载 dev 环境配置
  profiles:
    active: dev
    include: security

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    # 配置注册中心地址
    service-url:
      defaultZone: http://replica1:8001/eureka/

service-url:
  user-service: http://user-service
