server:
  port: 8003
spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: replica3
  client:
    serviceUrl:
      #注册到另一个Eureka注册中心
      defaultZone: http://replica1:8001/eureka/,http://replica2:8002/eureka/
    fetch-registry: true
    register-with-eureka: true
  server:
    enable-self-preservation: false #关闭保护模式（开发环境）
