server:
  port: 8001
spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: replica1
  client:
    serviceUrl:
      #注册到另一个Eureka注册中心
      defaultZone: http://replica2:8002/eureka/,http://replica3:8003/eureka/
    fetch-registry: true
    register-with-eureka: true
  server:
    enable-self-preservation: false #关闭保护模式（开发环境）
